# -*- coding: utf-8 -*-
# Манифест пачки 2 иконок биомов (34 недостающих из 57) — стиль B (мини-пейзаж).
# Образец стиля — принятая пачка 1 (biome_manifest.py). В промптах/негативах — запрет небесных тел.

STYLE_B = ', miniature stylized landscape scene, game icon, simple flat shapes, horizon, atmosphere, clean empty sky with clouds and haze, no sun, no moon, no planets, no stars, no celestial bodies in the sky, game asset, centered, on pure solid black background, no text, no watermark, no perspective'

# id = имя файла и биома из config/biome_catalog.json
ITEMS = [
    {'id': 'горы', 'name': 'Горы', 'sil': 'silB2_горы.png',
     's1': 'rocky mountain range with sharp snowy peaks, layered ridges, pale cold sky with clouds' + STYLE_B},
    {'id': 'пески_пустыни', 'name': 'Пески пустыни', 'sil': 'silB2_пески_пустыни.png',
     's1': 'desert sand dunes, rippled sand ridges under warm hazy pale sky' + STYLE_B},
    {'id': 'кратеры', 'name': 'Кратеры', 'sil': 'silB2_кратеры.png',
     's1': 'impact crater field, round craters with raised rims, grey rocky ground, dark hazy sky' + STYLE_B},
    {'id': 'каменные_пустоши', 'name': 'Каменные пустоши', 'sil': 'silB2_каменные_пустоши.png',
     's1': 'rocky wasteland, scattered boulders and flat stones, grey barren ground, overcast sky' + STYLE_B},
    {'id': 'соляные_чаши', 'name': 'Соляные чаши', 'sil': 'silB2_соляные_чаши.png',
     's1': 'white salt flat basins with polygonal cracked crust, bright pale sky' + STYLE_B},
    {'id': 'раковинная_пустыня', 'name': 'Раковинная пустыня', 'sil': 'silB2_раковинная_пустыня.png',
     's1': 'fossil shell desert, spiral shells half buried in pale bone sand, faint haze sky' + STYLE_B},
    {'id': 'танцующие_пески', 'name': 'Танцующие пески', 'sil': 'silB2_танцующие_пески.png',
     's1': 'desert dust devils, swirling sand columns on dune ridges, hazy tan sky' + STYLE_B},
    {'id': 'грозовая_степь', 'name': 'Грозовая степь', 'sil': 'silB2_грозовая_степь.png',
     's1': 'stormy iron steppe, dark storm clouds with lightning flashes, red-brown grass plains' + STYLE_B},
    {'id': 'углеродные_нагорья', 'name': 'Углеродные нагорья', 'sil': 'silB2_углеродные_нагорья.png',
     's1': 'black carbon highlands, dark graphite rock ridges and terraces, dim grey sky' + STYLE_B},
    {'id': 'металлорудные_возвышенности', 'name': 'Металлорудные возвышенности', 'sil': 'silB2_металлорудные_возвышенности.png',
     's1': 'metallic ore hills, rust stained rock ridges with ore veins, grey sky' + STYLE_B},
    {'id': 'металлические_поля', 'name': 'Металлические поля', 'sil': 'silB2_металлические_поля.png',
     's1': 'metallic plains, shiny steel plates and panels across flat ground, grey overcast sky' + STYLE_B},
    {'id': 'обсидиановые_поля', 'name': 'Обсидиановые поля', 'sil': 'silB2_обсидиановые_поля.png',
     's1': 'obsidian field, glossy black volcanic glass shards on dark ground, dark ashen sky' + STYLE_B},
    {'id': 'венерианские_плоскогорья', 'name': 'Венерианские плоскогорья', 'sil': 'silB2_венерианские_плоскогорья.png',
     's1': 'venusian highlands, dense orange yellow haze, cracked rocky plateau with steep cliffs' + STYLE_B},
    {'id': 'криовулканические_поля', 'name': 'Криовулканические поля', 'sil': 'silB2_криовулканические_поля.png',
     's1': 'cryovolcanic field, icy geysers erupting plumes, blue white frost ground, cold sky' + STYLE_B},
    {'id': 'озёра_реки', 'name': 'Озёра и реки', 'sil': 'silB2_озёра_реки.png',
     's1': 'lakes and winding rivers, blue water between green banks, soft sky with clouds' + STYLE_B},
    {'id': 'мелководья_заливные', 'name': 'Мелководья заливные', 'sil': 'silB2_мелководья_заливные.png',
     's1': 'flooded shallow flats, thin clear blue water over mudflats and sandbars, pale sky' + STYLE_B},
    {'id': 'планктонные_моря', 'name': 'Планктонные моря', 'sil': 'silB2_планктонные_моря.png',
     's1': 'plankton sea, green glowing water surface with streaks, teal hazy sky' + STYLE_B},
    {'id': 'термальные_террасы', 'name': 'Термальные террасы', 'sil': 'silB2_термальные_террасы.png',
     's1': 'thermal terraces, stepped turquoise and orange mineral pools with steam, pale sky' + STYLE_B},
    {'id': 'аммиачные_крио-океаны', 'name': 'Аммиачные крио-океаны', 'sil': 'silB2_аммиачные_крио-океаны.png',
     's1': 'ammonia cryo ocean, pale pinkish white liquid sea with slabs of ice, hazy cold sky' + STYLE_B},
    {'id': 'подлёдные_океаны', 'name': 'Подлёдные океаны', 'sil': 'silB2_подлёдные_океаны.png',
     's1': 'subglacial ocean, thick ice sheet with dark crack opening revealing water, cold sky' + STYLE_B},
    {'id': 'co2_океаны', 'name': 'CO₂-океаны', 'sil': 'silB2_co2_океаны.png',
     's1': 'CO2 ocean, yellowish tan liquid sea with faint waves, hazy amber sky' + STYLE_B},
    {'id': 'ледники', 'name': 'Ледники', 'sil': 'silB2_ледники.png',
     's1': 'glacier field, towering blue ice walls with deep crevasses, icy pale sky' + STYLE_B},
    {'id': 'мёрзлые_газы', 'name': 'Мёрзлые газы', 'sil': 'silB2_мёрзлые_газы.png',
     's1': 'frozen gas plains, icy cryo mounds and frost vents emitting pale mist, cold sky' + STYLE_B},
    {'id': 'азотно-ледяная_тундра', 'name': 'Азотно-ледяная тундра', 'sil': 'silB2_азотно-ледяная_тундра.png',
     's1': 'nitrogen ice tundra, flat pale blue ice plains with frost patches, pale cold sky' + STYLE_B},
    {'id': 'сухой_лёд', 'name': 'Сухой лёд', 'sil': 'silB2_сухой_лёд.png',
     's1': 'dry ice surface, white sublimating ice blocks with low fog, pale cold sky' + STYLE_B},
    {'id': 'джунгли', 'name': 'Джунгли', 'sil': 'silB2_джунгли.png',
     's1': 'dense jungle, tall layered tropical canopy with vines and giant leaves, humid green haze sky' + STYLE_B},
    {'id': 'тихие_рощи_низкой_гравитации', 'name': 'Тихие рощи низкой гравитации', 'sil': 'silB2_тихие_рощи_низкой_гравитации.png',
     's1': 'low gravity grove, very tall thin trees with sparse high crowns, quiet dusk sky' + STYLE_B},
    {'id': 'блуждающие_рощи', 'name': 'Блуждающие рощи', 'sil': 'silB2_блуждающие_рощи.png',
     's1': 'wandering grove, tilted walking trees with exposed roots on dusty plain, hazy sky' + STYLE_B},
    {'id': 'металлические_рощи', 'name': 'Металлические рощи', 'sil': 'silB2_металлические_рощи.png',
     's1': 'metallic grove, grey metal trees with steel trunks and angular crowns, overcast sky' + STYLE_B},
    {'id': 'радиационные_ковры', 'name': 'Радиационные ковры', 'sil': 'silB2_радиационные_ковры.png',
     's1': 'radiation carpets, glowing green flat mats with veins across dark ground, dim sky' + STYLE_B},
    {'id': 'карбидно-алмазные_заросли', 'name': 'Карбидно-алмазные заросли', 'sil': 'silB2_карбидно-алмазные_заросли.png',
     's1': 'carbide diamond thicket, sharp faceted diamond spikes and dark carbide shards, dark sky' + STYLE_B},
    {'id': 'радиационные_пустоши', 'name': 'Радиационные пустоши', 'sil': 'silB2_радиационные_пустоши.png',
     's1': 'radiation wasteland, barren ground with glowing green rocks and cracks, dark hazy sky' + STYLE_B},
    {'id': 'пружинная_тундра', 'name': 'Пружинная тундра', 'sil': 'silB2_пружинная_тундра.png',
     's1': 'spring tundra, coiled spring shaped plants on flat mossy plain, pale sky' + STYLE_B},
    {'id': 'пещерный_мир_с_потолком', 'name': 'Пещерный мир с потолком', 'sil': 'silB2_пещерный_мир_с_потолком.png',
     's1': 'cave world with stone ceiling, stalactites hanging from above over rocky floor, dim warm light' + STYLE_B},
]
