# -*- coding: utf-8 -*-
# Манифест пачки 1 иконок биомов — стиль B (мини-пейзаж), 23 биома.
# ВАЖНО: в промптах и негативах — запрет небесных тел (no sun/moon/planet/star/celestial body).

STYLE_B = ', miniature stylized landscape scene, game icon, simple flat shapes, horizon, atmosphere, clean empty sky with clouds and haze, no sun, no moon, no planets, no stars, no celestial bodies in the sky, game asset, centered, on pure solid black background, no text, no watermark, no perspective'

ITEMS = [
    {'id': 'леса', 'name': 'Леса', 'sil': 'silB_леса.png',
     's1': 'pine forest strip on the horizon, dark green tree crowns, pale blue sky with clouds' + STYLE_B},
    {'id': 'луга_степи', 'name': 'Луга и степи', 'sil': 'silB_луга_степи.png',
     's1': 'rolling meadow hills with grass tufts and small yellow flowers, pale sky with clouds' + STYLE_B},
    {'id': 'океаны', 'name': 'Океаны', 'sil': 'silB_океаны.png',
     's1': 'ocean horizon, blue sea with wave crests, white foam line, pale sky with clouds' + STYLE_B},
    {'id': 'болота', 'name': 'Болота', 'sil': 'silB_болота.png',
     's1': 'murky swamp with cattail reeds, low fog over dark water, greenish sky' + STYLE_B},
    {'id': 'коралловые_рифы', 'name': 'Коралловые рифы', 'sil': 'silB_коралловые_рифы.png',
     's1': 'shallow coral reef sea, teal water, pink and purple coral branches above the waterline' + STYLE_B},
    {'id': 'светящиеся_чащи', 'name': 'Светящиеся чащи', 'sil': 'silB_светящиеся_чащи.png',
     's1': 'dusk glowing thicket, dark trees with cyan glowing dots, twilight haze' + STYLE_B},
    {'id': 'багровые_степи', 'name': 'Багровые степи', 'sil': 'silB_багровые_степи.png',
     's1': 'crimson steppe, red grass tufts, hazy reddish sky, wind streaks' + STYLE_B},
    {'id': 'кислотные_дебри', 'name': 'Кислотные дебри', 'sil': 'silB_кислотные_дебри.png',
     's1': 'acidic thicket, spiky acid-green plants, slime puddle, green haze' + STYLE_B},
    {'id': 'серные_поля', 'name': 'Серные поля', 'sil': 'silB_серные_поля.png',
     's1': 'sulfur plains, yellow crystal clusters, steam vents, hazy yellow sky' + STYLE_B},
    {'id': 'хемосинтетические_сады', 'name': 'Хемосинтетические сады', 'sil': 'silB_хемосинтетические_сады.png',
     's1': 'dark chemosynthetic gardens, tube chimneys with teal glow, black haze' + STYLE_B},
    {'id': 'химический_иней', 'name': 'Химический иней', 'sil': 'silB_химический_иней.png',
     's1': 'chemical frost, tall white frost spikes on dark ground, pale icy sky' + STYLE_B},
    {'id': 'метановые_моря', 'name': 'Метановые моря', 'sil': 'silB_метановые_моря.png',
     's1': 'methane sea horizon, pale blue wave crests, hazy atmosphere, cloudy sky' + STYLE_B},
    {'id': 'углеводородные_равнины', 'name': 'Углеводородные равнины', 'sil': 'silB_углеводородные_равнины.png',
     's1': 'hydrocarbon plains, dark ground with black tar pools, smog sky, vent tower' + STYLE_B},
    {'id': 'инеевые_рощи', 'name': 'Инеевые рощи', 'sil': 'silB_инеевые_рощи.png',
     's1': 'frost grove, pale white frost-covered trees, icy white sky with clouds' + STYLE_B},
    {'id': 'лавовые_поля', 'name': 'Лавовые поля', 'sil': 'silB_лавовые_поля.png', 'lava': True,
     's1': 'lava fields, dark rock plates with glowing orange lava cracks, smoky orange sky' + STYLE_B},
    {'id': 'магмовый_океан', 'name': 'Магмовый океан', 'sil': 'silB_магмовый_океан.png', 'lava': True,
     's1': 'magma ocean, molten orange-red waves, glowing sky' + STYLE_B},
    {'id': 'вулканические_поля', 'name': 'Вулканические поля', 'sil': 'silB_вулканические_поля.png', 'lava': True,
     's1': 'volcanic fields, dark volcano cones with lava flows, ash sky' + STYLE_B},
    {'id': 'стеклянные_поля', 'name': 'Стеклянные поля', 'sil': 'silB_стеклянные_поля.png',
     's1': 'glass fields, translucent blue glass shards on dark ground, hazy blue sky' + STYLE_B},
    {'id': 'кристальные_рощи', 'name': 'Кристальные рощи', 'sil': 'silB_кристальные_рощи.png',
     's1': 'crystal grove, purple and cyan crystal spires, twilight sky' + STYLE_B},
    {'id': 'кремниевые_рощи', 'name': 'Кремниевые рощи', 'sil': 'silB_кремниевые_рощи.png',
     's1': 'silicon grove, grey teal spires, hazy teal sky' + STYLE_B},
    {'id': 'металлические_щетинные_поля', 'name': 'Металлические щетинные поля', 'sil': 'silB_металлические_щетинные_поля.png',
     's1': 'metal bristle field, dense steel needles, grey overcast sky' + STYLE_B},
    {'id': 'струнные_рощи', 'name': 'Струнные рощи', 'sil': 'silB_струнные_рощи.png',
     's1': 'string grove, thin vertical glowing strings, dusk sky' + STYLE_B},
    {'id': 'терминаторная_зона', 'name': 'Терминаторная зона', 'sil': 'silB_терминаторная_зона.png',
     's1': 'terminator zone, bright day side and dark night side with curved boundary, clear sky' + STYLE_B},
]